### ISSUE TITLE
Sync API support

### ISSUE THREAD

**Issue by penberg** [libsql/libsql-client-rs#15]
There's an example with Spin that uses some hacks to work in sync context:

https://github.com/psarna/country-counter-spin/blob/f6ff73488a1e31eba8ba60d5bb3dbb61c7686ce5/src/lib.rs#L68

Let's turn that into a proper API that's easy to use.

**Comment by psarna** [comment]
Done with 0.23.0, the demo is ported as well: https://github.com/psarna/country-counter-spin/blob/master/src/lib.rs#L70-L73

**Comment by psarna** [comment]
Note that only Spin backend has this sync API for now
